### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by drasmuss** [ctn-archive/nengo_spinnaker_2014#27]
I'm here at capocaccia, and there's been some talk of trying to get our PES learning rule running on Spinnaker.  I wanted to check with you @tcstewar and @mundya to get your thoughts.  Did you have any plans already for how to go about that?  Should I just go for it, or is there something blocking that in the current setup?

**Comment by celiasmith** [comment]
Just 'fyi', this has actually been 'done' in this paper:
http://compneuro.uwaterloo.ca/publications/davies2013.html

but i suspect it would be good to do again in the actual backend...

-c

drasmuss wrote:

**Comment by drasmuss** [comment]
Yeah the hope would be to make it compatible with the new pacman rewrite, as well as integrate it into nengo_spinnaker.  

Also now that we've got the decoders actually on the board, we should be able to do the decoder-level learning rather than synaptic.

**Comment by mundya** [comment]
@drasmuss There was some talk of doing this at the Waterloo summer school...

My main concern is that the backend isn't completely stable yet (i.e., things may yet change quite severely).  Also, I'm guessing it will hurt you that we aren't currently passing spikes between Ensembles?

EDIT: You answered that question!

Have you chatted with Jonathan/Jamie about this?  You'll need some PACMAN103 knowledge handy.

**Comment by tcstewar** [comment]
Yay learning!  The plan is that it should be pretty straightforward to do decoder learning in the setup we have.  The idea is that there would be a separate input (that wouldn't get summed [here](https://github.com/ctn-waterloo/nengo_spinnaker/blob/master/spinnaker_components/common/filtered-input.c#L85)) that would be the error signal.   It would be used to update the decoders in https://github.com/ctn-waterloo/nengo_spinnaker/blob/master/spinnaker_components/ensemble/ensemble-update.c

So that should be somewhat straightforward, with the caveat of watching out for the face that this is a fixed-point implementation, and we're using the fun new embedded C stuff that lets you write 0.0k and it's interpretted as a fixed point number.  Getting the casting straight in one's head for all that is a pain, but should be doable.

The other side of things is how to tell PACMAN103 about this system, and how to set parameters and whatnot on that.  That I'm less clear on, but hopefully Andrew or the people local there can help guide through that process.

**Comment by mundya** [comment]
> Getting the casting straight in one's head for all that is a pain, but should be doable.

This has caught me out _so_ many times: it's `bitsk(value)` if `value` is a fixed-point type (e.g., `value_t`) and you want a bitwise representation, and `kbits(value)` if `value` is a bitwise representation and you want a fixed-point value.  Any other way will do this exceptionally annoying cast which scales values by 2^15.

> The other side of things is how to tell PACMAN103 about this system, and how to set parameters and whatnot on that. That I'm less clear on, but hopefully Andrew or the people local there can help guide through that process.

I'm certainly happy to help via. email, but I sincerely recommend grabbing either Jonathan or Jamie (both of whom know some of nengo_spinnaker codebase) and getting their help on site.

**Comment by mundya** [comment]
@neworderofjamie implemented PES and this was merged in a while back.
