### ISSUE TITLE
Oscillator Unstable

### ISSUE THREAD

**Issue by mossblaser** [ctn-archive/nengo_spinnaker_2014#73]
The following oscillator was written by @celiasmith as part of a larger demo and unfortunately it behaves in an unstable manner on SpiNNaker.

```
import nengo
import numpy as np
from nengo.utils.functions import piecewise

tau = 0.01
w   = 0.1

model = nengo.Network(label='Handwriting')
with model:
    osc_pop = nengo.Ensemble(500, dimensions=2, radius = 1, label="Oscillator")

    input1 = nengo.Node(piecewise({0: [1, 0], 5.1: [0, 0]}), label="input")

    nengo.Connection(input1, osc_pop, synapse=tau) 
    nengo.Connection(osc_pop, osc_pop, transform = [[1,-w],[w,1]], synapse = 0.1)
    p = nengo.Probe(osc_pop)

from matplotlib import pyplot as plt
plt.figure()


runtime = 60

import nengo_spinnaker
sim = nengo_spinnaker.Simulator(model)
sim.run(runtime)

plt.subplot(211)
plt.plot(sim.trange(), sim.data[p], label="SpiNNaker")
plt.legend()
plt.xlabel("Time / s")
plt.ylim([-1, 1])

sim = nengo.Simulator(model)
sim.run(runtime)

plt.subplot(212)
plt.plot(sim.trange(), sim.data[p], label="Nengo Reference")
plt.legend()
plt.xlabel("Time / s")
plt.ylim([-1, 1])

plt.show(block=True)
```

Here is an example output compared with the reference simulator.

![unstable_oscillator](https://cloud.githubusercontent.com/assets/193514/3323639/31b507aa-f767-11e3-8a13-6c14e4572eb4.png)

**Comment by tcstewar** [comment]
Hmm..  odd...  definitely some difference happening there.  

Once quick thing to try is to make the oscillator increase in gain on its own.  Try this:

`nengo.Connection(osc_pop, osc_pop, transform = [[1.1,-w],[w,1.1]], synapse = 0.1)`

**Comment by mundya** [comment]
To rule out any routing/PACMAN/network issues you could also try dropping the size of the Ensemble to something under 128 neurons.

(Though if this were the case I'd expect to see the amplitude dropping much faster.)

**Comment by mundya** [comment]
Configured Node and
- 100 neurons:
  ![100neurons](https://cloud.githubusercontent.com/assets/3439837/3333659/f7b0dd74-f7f5-11e3-91e4-7fa4019da487.png)
- 200 neurons:
  ![200neurons](https://cloud.githubusercontent.com/assets/3439837/3333685/3e528e62-f7f6-11e3-994d-c30763a66e84.png)
- 500 neurons:
  ![500neurons](https://cloud.githubusercontent.com/assets/3439837/3333718/89fafb60-f7f6-11e3-91a6-e49120976e10.png)

_At this point I started dropping multicast packets at a very low rate_
- 1000 neurons:
  ![1000neurons](https://cloud.githubusercontent.com/assets/3439837/3333787/1ea9b26a-f7f7-11e3-9f72-1b0f522aae64.png)

I'm not sure what's happening.  The response appears to be stable but the amplitude is quite definitely down on where it should be, and that worsens with size of population.  At a guess we're not handling packets fast enough, but I'd expect to see some deformation of the output rather than just reduced amplitude.

As Terry suggests, modifying the transform corrects things: this is 200 neurons with `[[1.1, -w], [w, 1.1]]`:
![200neurons-gain](https://cloud.githubusercontent.com/assets/3439837/3333872/0a2c9b76-f7f8-11e3-9463-4b0d39e2b00c.png)

``` python
import nengo
import nengo_spinnaker
from nengo.utils.functions import piecewise

tau = 0.01
w   = 0.1

model = nengo.Network(label='Handwriting')
with model:
    osc_pop = nengo.Ensemble(200, dimensions=2, radius = 1, label="Oscillator")

    input1 = nengo.Node(piecewise({0: [1, 0], 5.1: [0, 0]}), label="input")

    nengo.Connection(input1, osc_pop, synapse=tau) 
    nengo.Connection(osc_pop, osc_pop, transform = [[1.1,-w],[w,1.1]], synapse = 0.1)
    p = nengo.Probe(osc_pop, synapse=0.05)


import nengo_spinnaker
config = nengo_spinnaker.Config()
config[input1].f_of_t = True
sim = nengo_spinnaker.Simulator(model, config=config)
sim.run(60.)

from matplotlib import pyplot as plt
from mpltools import style
style.use('ggplot')
plt.figure()

plt.subplot(211)
plt.plot(sim.trange(), sim.data[p], label="SpiNNaker")
plt.legend()
plt.xlabel("Time / s")
plt.ylim([-1, 1])

sim = nengo.Simulator(model)
sim.run(60.)

plt.subplot(212)
plt.plot(sim.trange(), sim.data[p], label="Nengo Reference")
plt.legend()
plt.xlabel("Time / s")
plt.ylim([-1, 1])

plt.show(block=True)
```

**Comment by mundya** [comment]
(Let's ignore frequency difference for now!)

**Comment by mundya** [comment]
Since merging in the host-refactor (mostly importantly c5bc90198da17b0713c1080f642b9fe7ac9e9e65) the oscillator in the examples directory remains in phase with the reference simulator.

**Comment by mundya** [comment]
I'm closing this, hopefully using a better fixed point value range will help and I'll try to get rolling on that soonish.
