### ISSUE TITLE
EnsembleArray breaks node pruning

### ISSUE THREAD

**Issue by mossblaser** [ctn-archive/nengo_spinnaker_2014#79]
It appears that the indirection via nodes done by EnsembleArrays breaks the node pruning routine when a connection is made from an EnsembleArray output node to something else which computes a function:

```
Traceback (most recent call last):
  File "simple_node_bug.py", line 23, in <module>
    sim = nengo_spinnaker.Simulator(model)
  File "/home/jonathan/Programing/spinnaker/nengo_summer_school/nengo_spinnaker/nengo_spinnaker/simulator.py", line 61, in __init__
    self.builder(model, dt, seed, node_builder=io, config=config)
  File "/home/jonathan/Programing/spinnaker/nengo_summer_school/nengo_spinnaker/nengo_spinnaker/builder.py", line 119, in __call__
    objs, connections)
  File "/home/jonathan/Programing/spinnaker/nengo_summer_school/nengo-temp/nengo/utils/builder.py", line 151, in remove_passthrough_nodes
    c = _create_replacement_connection(c_in, c_out)
  File "/home/jonathan/Programing/spinnaker/nengo_summer_school/nengo-temp/nengo/utils/builder.py", line 190, in _create_replacement_connection
    raise Exception('Cannot remove a Node with a '
Exception: Cannot remove a Node with a function being computed on it
```

A minimal script exhibiting this issue:

```
import nengo
from math import sin

D = 16

model = nengo.Network(label="Node removal bug example")
with model:
    def func(t):
        return [sin(t)]*D
    input = nengo.Node(func, label="input")

    en = nengo.networks.EnsembleArray(100, D, label="en")

    def printout(t,x):
        print t,x
    output = nengo.Node(printout, size_in=D, label="output")

    nengo.Connection(input, en.input)
    nengo.Connection(en.output, output, function=lambda xs: [-x for x in xs])

#sim = nengo.Simulator(model)
import nengo_spinnaker
sim = nengo_spinnaker.Simulator(model)

sim.run(1)
```

**Comment by mundya** [comment]
On reflection this isn't a bug, what your model is doing is actually pretty strange.

When you create an EnsembleArray you're creating a set of parallel Ensembles.  To make it easier for you to connect in to and out of the array two Nodes are created, the `input` and `output`.  These Nodes don't actually do anything, their job is to represent that whatever connects in to them should be able to connect straight onto anything they themselves connect to.

![path4762](https://cloud.githubusercontent.com/assets/3439837/3339249/bed91688-f868-11e3-8319-b8170dd56246.png)

If you apply a linear transform to any of the incoming or outgoing connections that's fine because linear transforms can be split up (i.e., 3(a+b+c) == 3a + 3b + 3c).  If, however, you apply a non-linear function that's not fine (i.e., (a+b+c)^2 =/= a^2 + b^2 + c^2).

Aside from the un-clear-ness of the Exception that gets raised I actually think nengo_spinnaker deals with this better than Nengo.  In Nengo it's advantageous that Pass Nodes are retained, and so the output from the Pass Node in the example does actually contain (a+b+c) and squaring that's not an issue.  _What that does mean is that the function is being applied non-neurally_, you're not modifying the decoders or limiting the representation, you get a perfectly linear square.

In nengo_spinnaker we remove Pass Nodes because (1) they'd be a waste of cores and (2) we can't apply arbitrary Python functions on chip.  We can't push the function back on to the incoming connections to the Pass Node because if it's non-linear that would change the input to subsequent blocks.  There's not really a fix here, Nengo could warn you about doing this, we could provide a clearer Exception...?  The issue really is that what you specify in the model isn't, I think, what you would actually like to be happening.

(Ignoring that the function you apply is linear) I think that the correct version of your example is this:

``` python
import nengo
from math import sin

D = 16

model = nengo.Network(label="Correctly computing stuff out of Pass Nodes")
with model:
    def func(t):
        return [sin(t)]*D
    input = nengo.Node(func, label="input")

    en = nengo.networks.EnsembleArray(100, D, label="en")
    en_output = nengo.Ensemble(100, D, label="en_output")

    def printout(t,x):
        print t,x
    output = nengo.Node(printout, size_in=D, label="output")

    nengo.Connection(input, en.input)
    nengo.Connection(en.output, en_output)
    nengo.Connection(en_output, output, function=lambda xs: [-x for x in xs])

#sim = nengo.Simulator(model)
import nengo_spinnaker
sim = nengo_spinnaker.Simulator(model)

sim.run(1)
```
